version: '3.8'
services:
  my_awsome_app:
    build: .
    volumes:
      - .:/online_school_project
    ports:
      - 8000:8000
    image: myapp:latest
    container_name: django_container
    command: python src/manage.py runserver 0.0.0.0:8000
